#!/usr/bin/env python3
"""Build the browser-readable expedition index from Markdown files in /logs."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parent
LOG_DIR = ROOT / "logs"
OUT = ROOT / "data" / "sessions.js"


def parse_value(value):
    value = value.strip()
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1]
    return value


def slugify(value):
    value = str(value or "").strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "diver"


def normalize_diver_status(value):
    value = str(value or "active").strip().lower()
    if value in {"dead", "deceased", "killed", "lost"}:
        return "deceased"
    return "active"


def parse_log(path: Path):
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    meta = {}
    body = text
    if text.startswith("---\n"):
        _, header, body = text.split("---\n", 2)
        for line in header.splitlines():
            if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
                continue
            key, value = line.split(":", 1)
            meta[key.strip()] = parse_value(value)

    raw_tags = meta.get("tags", "")
    tags = [x.strip() for x in raw_tags.split(",") if x.strip()]
    session_id = str(meta.get("id") or path.stem.split("-", 1)[0]).zfill(3)
    title = meta.get("title") or re.sub(r"[-_]", " ", path.stem).title()
    diver = meta.get("diver", "UNASSIGNED DIVER").strip() or "UNASSIGNED DIVER"
    diver_status = normalize_diver_status(meta.get("diver_status", "active"))
    diver_slug = slugify(diver)

    return {
        "id": session_id,
        "key": f"{diver_slug}-{session_id}",
        "diver": diver,
        "diver_slug": diver_slug,
        "diver_status": diver_status,
        "title": title,
        "date": meta.get("date", "DATE REDACTED"),
        "location": meta.get("location", "LOCATION UNKNOWN"),
        "status": meta.get("status", "ARCHIVED"),
        "tags": tags,
        "summary": meta.get("summary", "Expedition record awaiting summary."),
        "body": body.strip(),
        "source": path.name,
    }


logs = sorted(LOG_DIR.glob("*.md"))
sessions = [parse_log(path) for path in logs]
sessions.sort(key=lambda x: (x["date"], x["diver"].lower(), x["id"]), reverse=True)

# Catch the most common metadata mistake before deployment.
seen = {}
for session in sessions:
    if session["key"] in seen:
        raise SystemExit(
            f"Duplicate expedition number for {session['diver']}: LOG {session['id']} "
            f"appears in both {seen[session['key']]} and {session['source']}."
        )
    seen[session["key"]] = session["source"]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// AUTO-GENERATED by build.py. Edit files in /logs instead.\n"
    + "window.ATDW_SESSIONS = "
    + json.dumps(sessions, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"Built {len(sessions)} expedition log(s) -> {OUT.relative_to(ROOT)}")
